### ISSUE TITLE
Unit test error ACAD C3D 2024, Python 3.12.2

### ISSUE THREAD

**Issue by schoeller** [CEXT-Dan/PyRx#6]
Dear all,

when running `pytestall` under ACAD C3D 2024 I received the following error:

```python
======================================================================
FAIL: test_dbcore_strconversions (UnitTestPyDatabase.TestDatabase.test_dbcore_strconversions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\temp/pyrxgit/pyrx-main/unit tests\UnitTestPyDatabase.py", line 56, in test_dbcore_strconversions
    self.assertAlmostEqual(val, math.pi, 8)
AssertionError: 4.71238898038469 != 3.141592653589793 within 8 places (1.5707963267948966 difference)
======================================================================
FAIL: test_getSummaryInfo (UnitTestPyDatabase.TestDatabase.test_getSummaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\temp/pyrxgit/pyrx-main/unit tests\UnitTestPyDatabase.py", line 143, in test_getSummaryInfo
    self.assertEqual(info.asDict(), customDict)
AssertionError: {'Plansatz': 'Nein', 'Höhenbezug': 'DHHN', [1063 chars]Bug'} != {'Ford': 'Mustang', 'Chevy': 'Camaro', 'VW': ' Bug'}
Diff is 1322 characters long. Set self.maxDiff to None to see it.
----------------------------------------------------------------------
Ran 21 tests in 1.851s
FAILED (failures=2)
<unittest.runner.TextTestResult run=21 errors=0 failures=2>
pydbobject
----------------------------------------------------------------------

```

I am running Python 3.12.2 and `PyRx version <1.1.161.20240226>`. Please advise as of how to assist further as I am a scripter only.

Best regards

Sebastian

**Comment by CEXT-Dan** [comment]
Hi, thank you for running these tests, it’s very helpful

For the first test test_dbcore_strconversions we can replicate the test using Autolisp.
Db.Core.angToF is the same function as angtof in Autolisp.
https://help.autodesk.com/view/ACD/2022/ENU/?guid=GUID-9DE9200B-F27E-4BB6-8AE6-BC5C8A64A527

At the command line, please test the results of :    (angtof "180" 0) 

test_getSummaryInfo seems to be a bad test. It fails to consider if the drawing already has custom entries.
I will fix this

**Comment by CEXT-Dan** [comment]
@Canary818  Would it be possible for you to fix my goofy test? instead of comparing the dictionaries as a whole, 
check if the returned dictionary has the { key , value }

**Comment by schoeller** [comment]
> (angtof "180" 0)

@CEXT-Dan 
```lisp
Befehl: (angtof "180" 0)
4.71239
```

**Comment by CEXT-Dan** [comment]
Thank you, I see, you must have ANGBASE set to 90, whereas I have it at 0
I have corrected the test

**Comment by CEXT-Dan** [comment]
Hi, the tests should pass now.

**Comment by schoeller** [comment]
@CEXT-Dan: test passes flawlessly. Thanks for making your work opensource and for sharing your knowledge.

```lisp
Befehl: PYTESTALL
TestGe
----------------------------------------------------------------------
Ran 37 tests in 0.002s
OK
<unittest.runner.TextTestResult run=37 errors=0 failures=0>
pyrxobject
----------------------------------------------------------------------
Ran 5 tests in 0.000s
OK
<unittest.runner.TextTestResult run=5 errors=0 failures=0>
TestDatabase
----------------------------------------------------------------------
Ran 21 tests in 2.407s
OK
<unittest.runner.TextTestResult run=21 errors=0 failures=0>
pydbobject
----------------------------------------------------------------------
Ran 3 tests in 0.002s
OK
<unittest.runner.TextTestResult run=3 errors=0 failures=0>
TestDbObjectId
----------------------------------------------------------------------
Ran 2 tests in 0.000s
OK
<unittest.runner.TextTestResult run=2 errors=0 failures=0>
TestDbPoint
----------------------------------------------------------------------
Ran 1 test in 0.002s
OK
<unittest.runner.TextTestResult run=1 errors=0 failures=0>
TestDbEval
----------------------------------------------------------------------
Ran 2 tests in 0.000s
OK
<unittest.runner.TextTestResult run=2 errors=0 failures=0>
TestDbPoint
----------------------------------------------------------------------
Ran 23 tests in 1.545s
OK
<unittest.runner.TextTestResult run=23 errors=0 failures=0>
TestEditor
----------------------------------------------------------------------
Ran 3 tests in 0.008s
OK
<unittest.runner.TextTestResult run=3 errors=0 failures=0>
TestWxPython
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK
<unittest.runner.TextTestResult run=1 errors=0 failures=0>
```
